In [17]:
# EX 1.3.1
import numpy as np
A = np.zeros((8, 8))
A[1::2, ::2], A[0::2, 1::2] = 1, 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [24]:
# EX 1.3.2
A = np.zeros((5, 5)) + np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [26]:
#EX 1.3.3
A = np.random.random(((3, 3, 3)))
print(A)

[[[0.4030715  0.06625003 0.59568077]
  [0.90253335 0.68762664 0.05680338]
  [0.44640827 0.52588444 0.16329622]]

 [[0.76078991 0.82326169 0.10114054]
  [0.13099485 0.78888745 0.78362085]
  [0.62454944 0.12751803 0.69429175]]

 [[0.82894185 0.11552753 0.71911647]
  [0.11280308 0.2226859  0.09304955]
  [0.85454141 0.53475539 0.95446347]]]


In [40]:
# EX 1.3.4
x = int(input())
A = np.zeros((x, x))
for i in range(x):
    A[0][i], A[i][x-1], A[x-1][i], A[i][0] = 1, 1, 1, 1
print(A)

B = np.ones((x, x))
B[1:-1, 1:-1] = 0
print(B)

 5


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
# EX 1.3.5
x = [i for i in range(10)]
x.sort(reverse=True)
print(x)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [47]:
# EX 1.3.6
x = np.random.random(((3, 3, 3)))
print(x)
print(x.shape)
print(x.size)
print(x.itemsize)

[[[0.79675773 0.80384085 0.48904089]
  [0.40664309 0.49362941 0.7953062 ]
  [0.99359207 0.83091824 0.72960723]]

 [[0.77034043 0.95713938 0.91532231]
  [0.58150561 0.52296492 0.9204566 ]
  [0.76054627 0.06112936 0.61127316]]

 [[0.09523192 0.73741107 0.3143457 ]
  [0.15828407 0.46838156 0.70994962]
  [0.00722784 0.32459936 0.55431205]]]
(3, 3, 3)
27
8


In [8]:
# EX 2.3.1
a = np.array(([1, 2, 3, 4]))
b = np.array(([2, 3, 4, 5]))
s = np.square(a - b)
print(s)
summ = np.sum(s)
print(summ)
evk = np.sqrt(summ)
print(evk)

[1 1 1 1]
4
2.0


In [37]:
# EX 2.3.2
import pandas as pd
frame=pd.read_csv('pandas_tutorial_read.csv',  delimiter=';', names=['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])
frame.head()

my_datetime event    country     user_id   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

In [38]:
# EX 2.3.3
frame.tail(2)

my_datetime event    country     user_id   source   topic
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords  Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit    Asia

In [39]:
frame.shape

(1795, 6)

In [40]:
frame.describe()

user_id
count  1.795000e+03
mean   2.458152e+09
std    5.183162e+02
min    2.458151e+09
25%    2.458152e+09
50%    2.458152e+09
75%    2.458153e+09
max    2.458153e+09

In [41]:
frame.iloc[2:10]

my_datetime event    country     user_id   source          topic
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
5  2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America
6  2018-01-01 00:06:06  read  country_2  2458151267   Reddit         Europe
7  2018-01-01 00:06:15  read  country_6  2458151268  AdWords         Europe
8  2018-01-01 00:07:21  read  country_7  2458151269  AdWords  North America
9  2018-01-01 00:07:29  read  country_5  2458151270   Reddit  North America

In [42]:
frame[frame['country'] == 'country_8'].head(3)

my_datetime event    country     user_id   source          topic
4   2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
16  2018-01-01 00:13:05  read  country_8  2458151277      SEO  North America
45  2018-01-01 00:37:35  read  country_8  2458151306  AdWords           Asia

In [90]:
# EX 3.3.2
import pandas as pd
from sklearn.preprocessing import MinMaxScaler as mn
from sklearn.preprocessing import StandardScaler as sc
frame = pd.read_table('iris.txt', delimiter=",")

scaler = mn()
frame[['sepal_length_cm']] = scaler.fit_transform(frame[['sepal_length_cm']])

scaler = sc()
frame[['sepal_width_cm']] = scaler.fit_transform(frame1[['sepal_width_cm']])


frame

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]